### PR TITLE
Update scrollbars to match theme

### PR DESCRIPTION
**Pull request by sfc-gh-tteixeira**
## 📚 Context

Making scrollbars nicer looking.

**Note to reviewer:** Please navigate to every place on the website where you might find a scrollbar and see if this looks better than before / nothing is broken. Also try different browsers.

## 🧠 Description of Changes

**Before:**

before

**After:**

after

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by sfc-gh-dmatthews** [comment]
It looks like the color of the scrollbar for the AI chat in dark mode is off. I'll try to take a look, but feel free to update it if you see it faster @sfc-gh-tteixeira:
image

**Comment by sfc-gh-tteixeira** [comment]
How do I repro? Kapa doesn't work on this PR or localhost...

**Comment by sfc-gh-dmatthews** [comment]
@sfc-gh-tteixeira I just opened the dialog locally then made my browser really short to induce the scroll bar. There is another, lateral scroll bar that can show up in code examples, too, but I can only get to that to show up on the live site. (Trying to paste a generated answer into a local dev environment doesn't sufficiently pick up on style.)

image
image

**Comment by sfc-gh-tteixeira** [comment]
Fixed. Although now the dialog gets some ugly extra padding on the right when the scrollbar is present, which I don't like.

But I think this is mergeable.

It's so annoying how scrollbars break designs!

**Review by sfc-gh-dmatthews — APPROVED** [review]

**Pull request merged**
