### PR TITLE
Media links update

### LINKED ISSUE #653: Social Media Link Update
The social media links on the documentation site are missing some of the ones listed on the community section of streamlit.io.

Need to add Medium, LinkedIn, and Newsletter to match the main site. (Additionally, Reddit is missing, but that is also missing from the main site.)

I will submit a PR.

### PR DESCRIPTION
**Pull request by MathCatsAnd**
## 📚 Context
The documentation site is missing some of the newer social media links. Closes #653.

## 🧠 Description of Changes
Social media links were added to the social media callout and to the footer. SVGs were copied from the main site. Medium color copied from Discord (grey), LinkedIn color taken from their style docs, Newsletter color set to match "Streamlit red." (Reddit was not added since it is not on the main site yet, either). Links ordered to match main site, except GitHub was kept first due to its importance and to prevent adjacency to Medium (same color) on desktop view. Checked in both light and dark mode.

Note: The newsletter svg is an odd-one-out colored by stroke instead of fill. This may need to be updated if stronger consistency is desired. Additionally, it appears the existing Discord links are not in the official Discord blurple; that can get updated also if desired.

Size:
- [X] Small 

**Contribution License Agreement**
By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by MathCatsAnd** [comment]
image
image

**Review by snehankekre — APPROVED** [review]
These additions are wonderful, @MathCatsAnd! Kudos for taking the initiative!

LMK if you'd like to switch to Discord's official blurple. No strong need from our end. If not, happy to merge this PR as-is.

**Comment by MathCatsAnd** [comment]
I like pretty; I'll get that blurple in right now! 😸

**Comment by MathCatsAnd** [comment]
Blurple's up!

image

**Pull request merged**
