### PR TITLE
Replace hubspot newsletter form

### PR DESCRIPTION
**Pull request by sfc-gh-tteixeira**
## 📚 Context
Remove links to the Hubspot form since we're migrating away from that. This PR replaces it with a new form.

**Contribution License Agreement**
By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by sfc-gh-tteixeira** [comment]
Waiting for Krista's OK [here](https://snowflake.slack.com/archives/C04D47DRD39/p1723506662138909?thread_ts=1721671641.376539&cid=C04D47DRD39) before I merge.

**Comment by snehankekre** [comment]
The newsletter signup form has moved to https://info.snowflake.com/streamlit-newsletter-sign-up.html
It's linked on the main site: https://streamlit.io/community. Should we replace instead of remove, @sfc-gh-tteixeira?

**Comment by sfc-gh-tteixeira** [comment]
Up to @sfc-gh-kmuir !

The only reason I removed this was because she asked us to remove the form from [the blog](https://github.com/streamlit/blog-theme/pull/11)

**Comment by sfc-gh-dmatthews** [comment]
I'll follow up with Krista to confirm.

**Comment by sfc-gh-dmatthews** [comment]
Krista confirmed we can just update the links instead of delete it. I'll update this PR to do that.

**Review by sfc-gh-dmatthews — APPROVED** [review]

**Pull request merged**
