### PR TITLE
Fix ttl=None -> ttl=0 to disable caching in tutorials

### PR DESCRIPTION
**Pull request by sfc-gh-jcarroll**
## 📚 Context

Realized I had a brain fart last week and put in the wrong argument to disable caching in the two tutorials.

I scanned all the other docs and references, afaict this is the only place where I/we got it wrong. Also confirmed with Vincent that this new version is correct.

## 🧠 Description of Changes

- Switch `ttl=None` -> `ttl=0` for how to disable caching in the query methods of SQL and SnowparkConnection, as specified in the MySQL and Snowflake tutorials.

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by sfc-gh-jcarroll** [comment]
cc @vdonato @snehankekre

**Comment by snehankekre** [comment]
@sfc-gh-jcarroll The docstrings for the `query` [methods](https://deploy-preview-628--streamlit-docs.netlify.app/library/api-reference/connections/st.connections.sqlconnection#sqlconnectionquery), suggest the current version of setting `ttl=None` is correct. Could you confirm which is correct, @vdonato?

image

If setting `ttl=0` makes cache entries not expire, we should update the docstrings in core.

**Review by snehankekre — APPROVED** [review]
@sfc-gh-jcarroll The docstrings for the `query` [methods](https://deploy-preview-628--streamlit-docs.netlify.app/library/api-reference/connections/st.connections.sqlconnection#sqlconnectionquery), suggest the current version of setting `ttl=None` is correct; so does the type annot. Could you confirm which is correct, @vdonato?

image

image

If setting `ttl=0` makes cache entries not expire, we should update the docstrings in core.

**Comment by sfc-gh-jcarroll** [comment]
Both the docstrings and these updates are correct:

- `ttl = None` : Cache the result, and don't ever expire the cache and don't re-run the function as long as the server is running
- `ttl = 0` : Don't cache the result, re-run the function every time

**Comment by snehankekre** [comment]
Ah, thanks for clarifying! I re-read the docstrings and realised I was mistaken. `ttl=None` caches the query results indefinitely. This is not synonymous with _disabling_ caching.

**Pull request merged**
