### PR TITLE
[Refactor] Tile CSS

### PR DESCRIPTION
**Pull request by imjuangarcia**
Simplified this one quite a bit, since it had tons of configuration options, but it's only used on https://docs.streamlit.io/streamlit-cloud

### CODE REVIEW

**Review by tvst — CHANGES_REQUESTED** [review]
This breaks the tiles in the front page:

### This PR
image

###  Today
image

**Comment by imjuangarcia** [comment]
> This breaks the tiles in the front page

Fixed on [cdf0369](https://github.com/streamlit/docs/pull/293/commits/cdf0369831b824e37c3e898f1ab65968306d0b78)! Sorry I missed that

**Comment by tvst** [comment]
LGTM except need more padding top and add hover zoom effect

**Comment by imjuangarcia** [comment]
> LGTM except need more padding top and add hover zoom effect

Both fixed on [b18d31e](https://github.com/streamlit/docs/pull/293/commits/b18d31e92cba62b2c724a6a468346584cd436b3b)

**Pull request merged**
