### PR TITLE
Update sitemap generation workflow file

### PR DESCRIPTION
**Pull request by sfc-gh-jgarcia**
## 📚 Context

This PR polishes our GitHub Actions Workflow, and fixes our sitemap generation by creating a PR with the newly created sitemap after changes had been pushed to `main`

## 🧠 Description of Changes

* Updated `postbuild-scripts.yml`

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

## 🌐 References

- https://www.notion.so/snowflake-corp/Investigate-why-Docs-sitemap-is-not-generated-5d8e8bfcc24e40da9053def8192bd253?pvs=4

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Review by snehankekre — APPROVED** [review]
Thanks for tackling this @sfc-gh-jgarcia! LGTM.

Will every merge to `main` result in an automated PR like https://github.com/streamlit/docs/pull/650 ? Just curious is all.

**Review by snehankekre — APPROVED** [review]
Thanks for tackling this @sfc-gh-jgarcia! LGTM.

Will every merge to `main` result in an automated PR like https://github.com/streamlit/docs/pull/650 ? Just curious is all.

**Comment by sfc-gh-jgarcia** [comment]
> Will every merge to `main` result in an automated PR like #650 ? Just curious is all.

Yep! Another option is to commit and push the sitemap directly, instead of creating a PR, but I wasn't sure if we have branch protection rules for `main` in this repo. Maybe we can have them be merged automatically through dependabot or similar?

**Comment by snehankekre** [comment]
You're right, we do have [branch protection rules](https://github.com/streamlit/docs/settings/branch_protection_rules/22791533) in place. Only documentation admins can merge to main without a PR and reviewer approval. Merging them in automatically would be a better option (nice to have), although not a blocker.

I'll look up how to merge them automatically and I'm definitely open to suggestions if you know how :smile

**Comment by sfc-gh-jgarcia** [comment]
> I'll look up how to merge them automatically and I'm definitely open to suggestions if you know how

We could use another Github action, such as [this one](https://github.com/marketplace/actions/merge-pull-requests-automerge-action) but it does require some extra setup, like adding a GitHub token, and I'm not totally sure it'll still be able to bypass the branch protection rules

**Comment by snehankekre** [comment]
If it's unable to bypass branch protection rules, it's ok. It shouldn't be too much overhead to hit merge on bot generated sitemap PRs, as long as those PRs are in fact generated. 😄  The current is that only one such PR #650 was ever generated. Many PRs have since been merged to `main`, but subsequent sitemap PRs have been added.

**Comment by sfc-gh-jgarcia** [comment]
> If it's unable to bypass branch protection rules, it's ok. It shouldn't be too much overhead to hit merge on bot generated sitemap PRs, as long as those PRs are in fact generated. 😄 The current issue is that only one such PR #650 was ever generated. Many PRs have since been merged to `main`, but no subsequent sitemap PRs have been added.

That's because I had it so that every push would generate the sitemap, for testing purposes, but after everything here looked good, I reverted it so that only pushes to `main` would trigger the functionality.

That means we should merge this, and after that, subsequent merges to `main` will trigger the new sitemap generation. 

That's the theory, though 🤣

**Comment by snehankekre** [comment]
Cool! Let's test that by merging in that case 🤞

**Pull request merged**
