### PR TITLE
Remove global styles

### PR DESCRIPTION
**Pull request by imjuangarcia**
This PR deletes the global styles on the previous `.scss` styling version, and keeps everything within Tailwind.

It's a pretty big PR, not only because it deletes a bunch of the old styling, but also because after deleting those globals, a few of the components needed to be updated.

### CODE REVIEW

**Comment by tvst** [comment]
I think we lost the ::webkit-scrollbar rules in this PR. Can you re-add them?

**Comment by tvst** [comment]
I see weird text-underlines on the knowledgebase page

## This PR
image

## Original
image

**Comment by tvst** [comment]
"Suggest edits" lost its underline and hover state

## This PR
image

## Original
image

**Comment by tvst** [comment]
Padding below page titles is a bit too small

## This PR
image

## Original
image

**Comment by tvst** [comment]
Right-side nav showing weird underlines:

## This PR
image

## Original
image

**Comment by tvst** [comment]
Actually, the vertical padding issue doesn't only affect page titles, but also other title elements. See "Display almost anything" below. Plus, the headers inside those API chips are looking different than before.

## This PR
image

## Original
image

**Comment by tvst** [comment]
Normal text inside chips is too thin

## This PR
image

## Original
image

**Comment by tvst** [comment]
Line height in titles is too tight. (This may be the reason why vertical padding is different)

## This PR
image

## Original
image

**Comment by tvst** [comment]
Search pop-up issues:
1. Font weight too thin
2. Left icon not centered
3. X icon not centered (not shown in screenshots)

## This PR
image


## Original
image

**Comment by tvst** [comment]
Logo+"documentation" and sun buttons in the header lost hover state

image

**Comment by tvst** [comment]
These links lost their hover state
image

**Comment by imjuangarcia** [comment]
@tvst Thanks for the thorough review! The issues you mentioned should've been fixed on the following commits:

* Scrollbars: [368d152](https://github.com/streamlit/docs/pull/322/commits/368d152e262427dda7d9e54b4a2c6214d4f7a956)
* Weird text underlines on KB: [7f2f2ec](https://github.com/streamlit/docs/pull/322/commits/7f2f2ece2aa9941da7d7948a2ecaa9d14c3bb7d2)
* Fixes on suggest edits component: [8811963](https://github.com/streamlit/docs/pull/322/commits/8811963e9c2f2a806935a696125929bbdf545e1c)
* Updates on paddings, margins, line heights for titles: [a9ec0b0](https://github.com/streamlit/docs/pull/322/commits/a9ec0b013390f9536c198b712ae37ac267ad7a93) and [6fb28ef](https://github.com/streamlit/docs/pull/322/commits/6fb28eff3fad884470ead0510bc60e454dbbe477)
* Fix on underlines for floating nav: [25656cd](https://github.com/streamlit/docs/pull/322/commits/25656cd5822e628132163475e6e17dd6684ceed3)
* Update text styles on Reference Cards: [1460830](https://github.com/streamlit/docs/pull/322/commits/146083004eebe7cff17f24a8d070c6502b2c039b)
* Search Modal updates: [b139d4d](https://github.com/streamlit/docs/pull/322/commits/b139d4d92f6e92be64e18c4fe741c4890b5cd607)
* Hover states for header: [f8bca76](https://github.com/streamlit/docs/pull/322/commits/f8bca7635d43ae7dd092fefe8dedd1a134bea7d4)
* Hover states for callouts: [8ba4e58](https://github.com/streamlit/docs/pull/322/commits/8ba4e5882128618e96d3ae745880656e637b71d5)

**Comment by tvst** [comment]
Cheat sheet headers look different

(also, unrelated to this PR, the code colors on the cheatsheet are often hard to read... not sure what happened there)

## This PR
image

## Original 
image

**Comment by tvst** [comment]
Search icons are still not properly centered

## This PR
image


## Original
image

**Comment by tvst** [comment]
Version headers are bolder than other headers in the docs

## This PR
image

## Original
image

**Comment by tvst** [comment]
Questions in troubleshooting page wrong font size

## This PR
image


## Original
image

**Comment by imjuangarcia** [comment]
@tvst Thanks for the review! Find the adjustments below:

* Fix on font weight for cheatsheet headings [2333f07](https://github.com/streamlit/docs/pull/322/commits/2333f0777d9d096f53f828b3df221985b50cab0d);
* Improve legibility on cheatsheet code on light mode [e67a5b2](https://github.com/streamlit/docs/pull/322/commits/e67a5b243c6882536912eeca2a5684893b90dbb5);
* Horizontally center the search input icons [8859abb](https://github.com/streamlit/docs/pull/322/commits/8859abb9b19f2cd56750d3f9651b24772c6d1be6);
* Fix on font weight for Version titles on changelog [e0cda59](https://github.com/streamlit/docs/pull/322/commits/e0cda59eaf61ddb1cfd666b7af665859126aed24);
* Fix on heading sizes on troubleshooting page [63bce72](https://github.com/streamlit/docs/pull/322/commits/63bce7228db0f6bb3e204f956c4ee647d83be570)

**Comment by tvst** [comment]
Code block colors are different in new version vs old. The new one is less readable.

## This PR
image

## Prod
image

**Comment by tvst** [comment]
Focus outline looks different in this PR vs Prod.

## This PR
image
image

## Prod

image

image

**Comment by imjuangarcia** [comment]
> Focus outline looks different in this PR vs Prod.

Fixed on [a1be618](https://github.com/streamlit/docs/pull/322/commits/a1be61803e471ed04b241ef50776b6971e7bc941)

> Code block colors are different in new version vs old. The new one is less readable. I think this may be due to the Cheatsheet readability fix — but can we make this fix only apply to code blocks that don't have dark background?

Fixed on [c055d69](https://github.com/streamlit/docs/pull/322/commits/c055d69c889e7c65ee8668b6dcd5875ac7a76336)

**Review by tvst — APPROVED** [review]
:tada:

**Pull request merged**
