### PR TITLE
Update images to remove hamburger menu

### PR DESCRIPTION
**Pull request by sfc-gh-dmatthews**
The In-app menu was changed from a hamburger to a kebab. This commit updated the images on the App Menu page of the docs.

## 📚 Context
This is a fast-follow to update images for the new app menu documentation.

## 🧠 Description of Changes
Images showing the menu icon are replaced to show the new icon (/library/advanced-features/app-menu)

### Revised
https://deploy-preview-730--streamlit-docs.netlify.app/library/advanced-features/app-menu

## 💥 Impact
Size:
- [X] Small

## 🌐 References
- Notion: [Fast-follow, Docs for Config option to control hamburger menu](https://www.notion.so/snowflake-corp/FF-Update-App-Menu-docs-to-show-new-icon-7dec6e38efac441592ca6e5631ee01ec)

**Contribution License Agreement**
By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by sfc-gh-dmatthews** [comment]
Since this is just an image update, it can easily wait for the matching feature to get published without creating a conflict.

**Review by snehankekre — APPROVED** [review]

**Review by sfc-gh-jgarcia — APPROVED** [review]
LGTM 👍 FYI, the open-source changes were merged yesterday, so they should go live on the next release

**Comment by sfc-gh-dmatthews** [comment]
I've searched through the site for any other references to "hamburger" or "☰" and found about a dozen instances. One question: do we want to update where the changelog has mentioned the "hamburger" menu? I can see an argument for not touching anything in the changelog, but also for making sure those historical changes are recorded in icon-agnostic language except when explicitly saying the icon was changed. (e.g. Changing "cleaned up the hamburger menu" to "cleaned up the app menu") I have the edits on my local git, ready to push when I have confirmation on this point.

**Comment by snehankekre** [comment]
> One question: do we want to update where the changelog has mentioned the "hamburger" menu? 

The changelog should be historically accurate. Let's avoid rewriting it. In the next 1.25.0 changelog, we can mention the name change.

**Pull request merged**
