### PR TITLE
Add CSP and related headers

### PR DESCRIPTION
**Pull request by sfc-gh-tteixeira**
## 📚 Context

Let's harden our security policies!

## 🧠 Description of Changes

This PR adds the following headers to both `next.config.js` (for local development) and `netlify.toml` (for prod):
* [Strict-Transport-Security](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) - to force HTTPs
* [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) - to turn off content type sniffing (helps avoid injection of script and css hacks)
* [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) - to specify which external content we allow in our site, via an allow-list.

## 👀 How to review
* Review the code as usual
* **MOST IMPORTANTLY,** review the deploy preview, clicking through all links you can find. Make sure the JS console is open. CSP errors will appear in red.

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

## 🌐 References

- More info: https://www.notion.so/snowflake-corp/Streamlit-domain-vulnerabilities-32533973882d429daeb981ed53173d85

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Review by sfc-gh-dmatthews — DISMISSED** [review]

**Comment by sfc-gh-dmatthews** [comment]
The preview link is non-functional for me.
image

**Comment by sfc-gh-tteixeira** [comment]
Oh, I know 😃 . I spent some time debugging yesterday and found the problem: it's at markdown library we're using in the GDPR banner. I'll try to replace it.

**Comment by sfc-gh-dmatthews** [comment]
I'm getting errors on these pages:
* /get-started/installation/anaconda-distribution (POST)
* /library/api-reference (uncaught)
* /library/api-reference/write-magic/st.write (POST)
* /library/api-reference/write-magic/st.write_stream (POST)
* (I checked several other Autofunction pages, and got POST errors, too.)
* /library/advanced-features (uncaught)
* /library/advanced-features/dataframes (POST)
* /library/advanced-features/forms (POST)
* /library/advanced-features/multipage-apps/custom-navigation (POST)
* /library/advanced-features/widget-behavior (POST)

Let me know if you want more @sfc-gh-tteixeira.

**Comment by snehankekre** [comment]
> I'm getting errors on these pages:

Chiming in to say the listed errors occur on the live site today and may likely be unrelated to changes from this PR. The 403 response is from embedded apps denying `/api/v1/app/event/open` requests to sites not adhering to Cloud's `strict-origin-when-cross-origin` policy.

**Comment by sfc-gh-dmatthews** [comment]
I'm getting new red errors, even on the home page:
* Refused to connect
* Failed to fetch
* Failed to load Analytics.js
* Refused to connect

There is also a yellow error:
* Your CSP policy is missing permissions required in order to run Analytics.js 2.0.

I don't really know what I'm looking for besides opening each of the pages and reporting what I see in red in the console. So I'll mark the PR approved for you to merge when you get to the correct threshold. Let me know if you want me to click through more pages.

**Comment by snehankekre** [comment]
> I'm getting new red errors, even on the home page

@sfc-gh-dmatthews you're right!! Turns out my ublock Origin extension was blocking segment requests, so I didn't see the segment-specific CSP errors. I do see them now 👍 (thanks for mentioning Analytics.js; got me thinking about adblock extensions).

The POST errors and uncaught exceptions from https://github.com/streamlit/docs/pull/980#issuecomment-1980100445 are unrelated to this PR, but these segment ones are definitely CSP issues.

**Comment by sfc-gh-tteixeira** [comment]
@sfc-gh-dmatthews I think I have everything covered now. PTAL!

**Comment by sfc-gh-dmatthews** [comment]
### Definitely related to CSP headers:
* `auryc.worker.js:6 Refused to connect to 'https://mt.auryc.com/v1/event' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.streamlit.app/ wss://*.streamlit.app/ https://streamlit.ghost.io/ghost/api/ https://api.segment.io/ https://cdn.segment.com/ https://client-api.auryc.com/ https://www.google-analytics.com/ https://stats.g.doubleclick.net/".`


### Things that are probably not related to CSP headers:

* Errors related to embedded apps. (`POST ... 403 Forbidden`)
* `Uncaught Error: Minified React error #418` on the API reference page and generally on most pages with RefCards. Also shows on other pages with a hard refresh, but not if navigating there from another page. 🤔 
* `Prism doesn't support this language: none` on /streamlit-community-cloud/deploy-your-app/app-dependencies (I think I can fix that one myself. 😄)

**Review by sfc-gh-dmatthews — APPROVED** [review]

**Pull request merged**
