### PR TITLE
Ability to format breadcrumbs for pages that aren't on the menu

### PR DESCRIPTION
**Pull request by imjuangarcia**
This PR fixes the issue brought by @snehankekre [here](https://www.notion.so/streamlit/Fix-breadcrumb-formatting-for-Knowledge-Base-pages-411ab015964e4065900903232ab51a43) by adding a `visible` property on `menu.md`.

This property allow us to add entries to `menu.md`, creating their properly formatted breadcrumbs, but without showing the entries on the sidebar.

To try things out, add the following to `menu.md`:

```yml
- category: Knowledge base / Using Streamlit / How to download a file in Streamlit?
   url: /knowledge-base/using-streamlit/how-download-file-streamlit
   visible: false
```

----------------

**Before:**
Untitled

**After:**
Screen Shot 2022-02-14 at 17 32 20

Notice that the `visible: false` property prevents the page from showing up under `Using Streamlit` in the sidebar.

### CODE REVIEW

**Comment by tvst** [comment]
Can we throw an exception when the item doesn't exist in the menu? This will force developers to create a corresponding invisible menu item to fix it.

**Comment by snehankekre** [comment]
@imjuangarcia On 2b079cf, I've added entries in `menu.md` for the above URLs. The following URLs weren't supposed to exist, so I deleted their corresponding markdown files:

> /knowledge-base/errors
/knowledge-base/tutorials/rent-prices
/library/api-reference/code
/streamlit-cloud/additional-features

Would you mind adding something about this behavior to `README.md`?

**Comment by snehankekre** [comment]
@imjuangarcia The build might be failing due to the redirect we set up for `/library/ -> /library/get-started/`. I'm unsure how to fix that. :sweat_smile:

**Comment by imjuangarcia** [comment]
> @imjuangarcia The build might be failing due to the redirect we set up for /library/ -> /library/get-started/. I'm unsure how to fix that. 😅

@snehankekre according to the logs on Netlify, it seems like there's still a file, `rent-price.md` inside `kb -> tutorials`, that doesn't have an entry in `menu.md`

**Comment by snehankekre** [comment]
Whoops, fixed on 6215635.

**Comment by imjuangarcia** [comment]
> Whoops, fixed on [6215635](https://github.com/streamlit/docs/commit/621563598ed961c263e6e25aedac493c31fb63d7).

Awesome, thanks! The build is now working again 🎉. I've also updated the `README.md` file on [2ffcb3a](https://github.com/streamlit/docs/pull/311/commits/2ffcb3ad80abbaec9c813a2ff71561429195bb17)

**Review by tvst — APPROVED** [review]

**Pull request merged**
