### PR TITLE
Update syntax highlighting colors

### PR DESCRIPTION
**Pull request by imjuangarcia**
## 📚 Context

This PR fixes [this issue](https://www.notion.so/streamlit/Doc-papercut-code-looking-too-crazy-9d1d50f251684299b2d681e0cce27473) brought by @tvst where the color selected for `@decorators` makes the code tiles look too colorful.

## 🧠 Description of Changes

* Updated the colors for `.operator` and `.decorator` in both light and dark modes in `code.module.css`;

**Revised:**

Screen Shot 2022-10-11 at 4 15 38 PM

Screen Shot 2022-10-11 at 4 15 30 PM

**Current:**

Screen Shot 2022-09-28 at 16 08 18

## 💥 Impact

Size:

- [x] Small 
- [ ] Not small 

## 🌐 References

- https://www.notion.so/streamlit/Doc-papercut-code-looking-too-crazy-9d1d50f251684299b2d681e0cce27473

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the Apache 2.0 license.

### CODE REVIEW

**Comment by imjuangarcia** [comment]
> What if we reduced the number of colors? For example: use same color as function names, and make function names bold.

Done! Updated in [a167dc5](https://github.com/streamlit/docs/pull/501/commits/a167dc518074a774b2701e84c289ee05ae098582)

**Review by snehankekre — APPROVED** [review]
Thanks, Juan! The changes in a167dc5 look much better

**Comment by sfc-gh-tteixeira** [comment]
Can you make the same changes here?
Screen Shot 2022-10-17 at 11 25 20

**Comment by imjuangarcia** [comment]
@sfc-gh-tteixeira sure thing! Updated in [c151c99](https://github.com/streamlit/docs/pull/501/commits/c151c998ecc383ae427067605e94578a90c533ad)

**Review by sfc-gh-tteixeira — APPROVED** [review]

**Pull request merged**
