### PR TITLE
Fix on sharing image URL

### PR DESCRIPTION
**Pull request by imjuangarcia**
This PR intends to fix the issue brought by @CharlyWargnier where thumbnail images aren't showing up when sharing content on twitter

### CODE REVIEW

**Review by snehankekre — APPROVED** [review]
LGTM @imjuangarcia! I had assumed, incorrectly, that we would have to add unique thumbnails to each article page.

**Comment by imjuangarcia** [comment]
> LGTM @imjuangarcia! I had assumed, incorrectly, that we would have to add unique thumbnails to each article page.

That'd be another way to go about it. We have the ability to do that on the website, and default to the logo image when nothing is added. For the docs' site, I feel it's going to be _a lot_ of work, that's why I kept the default image on all pages, but LMK if you prefer otherwise!

**Comment by snehankekre** [comment]
In that case, let's not pursue it. There are other eng and content tasks that take precedence.

**Comment by randyzwitch** [comment]
For sure on the custom images part, maybe we can get an intern to do that

**Pull request merged**
