### PR TITLE
Update 'No dependency file' Section

### PR DESCRIPTION
**Pull request by raethlein**

### CODE REVIEW

**Comment by randyzwitch** [comment]
This is a product decision for sure, but it feels weird for us to document behavior from indeterminate states. Meaning, this feels like an internal design decision that could just as easily be changed in the future; should we just be telling users to explicitly set the version in their requirements or risk getting undesired behavior?

**Comment by raethlein** [comment]
@randyzwitch good point, that would also be totally fine for me and I don't have a strong opinion here. I just wanted to create this PR so it does not get lost that the Section seems to need an update

**Review by atoader — APPROVED** [review]

**Comment by snehankekre** [comment]
@raethlein @randyzwitch I've added a small paragraph on 39aa3bb to clarify that using a dependency file and pinning a version of Streamlit is the best practice, if users want to avoid undesired behavior. WDYT?

**Review by snehankekre — APPROVED** [review]

**Comment by randyzwitch** [comment]
Looks good, thanks @snehankekre!

**Pull request merged**
